#!/bin/bash
source /opt/apps/geograph/current/script/cloud/nimbus/set_app_env.sh
sh $GEOGRAPH_HOME/script/cloud/nimbus/log.sh "3-data/geograph" "invoked"

$JRUBY_HOME/bin/jruby -S $GEOGRAPH_HOME/script/cloud/set_db_host.rb "geograph" "geograph" && sh $GEOGRAPH_HOME/script/cloud/nimbus/log.sh "3-data/geograph" "db host set"
