#!/bin/bash
/opt/torquebox/current/jruby/bin/jruby -S /opt/apps/geograph/current/script/cloud/set_modcluster_host.rb
service jboss-as-standalone stop
/etc/init.d/mysqld stop
/opt/jboss/httpd/sbin/apachectl start
