#!/bin/bash
source /opt/apps/geograph/current/script/cloud/nimbus/set_app_env.sh
sh $GEOGRAPH_HOME/script/cloud/nimbus/log.sh "3-data/usersdb" "invoked"

/opt/jboss/httpd/sbin/apachectl stop && sh $GEOGRAPH_HOME/script/cloud/nimbus/log.sh "3-data/usersdb" "apache stopped"

service jboss-as-standalone stop && sh $GEOGRAPH_HOME/script/cloud/nimbus/log.sh "3-data/usersdb" "jboss stopped"

/etc/init.d/mysqld restart && sh $GEOGRAPH_HOME/script/cloud/nimbus/log.sh "3-data/usersdb" "mysql started"
