#!/bin/bash
#This script is called by each node that requires geograph,
#and is invoked with the ip and host as parameters (as many times
#as the number of nodes with a geograph role)

sh /opt/apps/geograph/current/script/cloud/nimbus/log.sh "1-ipandhost/geograph" "invoked with $3"

/opt/torquebox/current/jruby/bin/jruby -S /opt/apps/geograph/current/script/cloud/add_node.rb "cluster_nodes" $3 && sh /opt/apps/geograph/current/script/cloud/nimbus/log.sh "1-ipandhost/geograph" "add_node.rb invoked"
