#!/bin/bash
#This script is called by each node that requires geograph,
#and is invoked with the ip and host as parameters (as many times
#as the number of nodes with a geograph role)

/opt/torquebox/current/jruby/bin/jruby -S /opt/apps/geograph/current/script/cloud/add_node.rb "cluster_nodes" $3
