#!/bin/bash
sh /opt/apps/geograph/current/script/cloud/nimbus/log.sh "4-restarts/geograph" "invoked geograph app server script"

/opt/torquebox/current/jruby/bin/jruby -S /opt/apps/geograph/current/script/cloud/set_torquebox_host.rb && sh /opt/apps/geograph/current/script/cloud/nimbus/log.sh "4-restarts/geograph" "setted host"

/opt/jboss/httpd/sbin/apachectl stop && sh /opt/apps/geograph/current/script/cloud/nimbus/log.sh "4-restarts/geograph" "stopped mod_cluster"

/etc/init.d/mysqld stop && sh /opt/apps/geograph/current/script/cloud/nimbus/log.sh "4-restarts/geograph" "stopped mysqld"

cd /opt/apps/geograph/current && RAILS_ENV=production jruby -S bundle exec rake torquebox:deploy && sh /opt/apps/geograph/current/script/cloud/nimbus/log.sh "4-restarts/geograph" "geograph deployed"

service jboss-as-standalone restart && sh /opt/apps/geograph/current/script/cloud/nimbus/log.sh "4-restarts/geograph" "restarted torquebox"
