#!/bin/bash
source /opt/apps/geograph/current/script/cloud/nimbus/set_app_env.sh
sh $GEOGRAPH_HOME/script/cloud/nimbus/log.sh "4-restarts/geograph-mod-cluster" "invoked geograph app server script"

$JRUBY_HOME/bin/jruby -S $GEOGRAPH_HOME/script/cloud/set_torquebox_host.rb "geograph" && sh $GEOGRAPH_HOME/script/cloud/nimbus/log.sh "4-restarts/geograph-mod-cluster" "setted host"

/opt/jboss/httpd/sbin/apachectl stop && sh $GEOGRAPH_HOME/script/cloud/nimbus/log.sh "4-restarts/geograph-mod-cluster" "stopped mod_cluster"

/etc/init.d/mysqld stop && sh $GEOGRAPH_HOME/script/cloud/nimbus/log.sh "4-restarts/geograph-mod-cluster" "stopped mysqld"

su - torquebox -c "cd $GEOGRAPH_HOME && RAILS_ENV=production $JRUBY_HOME/bin/jruby -S bundle exec rake torquebox:deploy" && sh $GEOGRAPH_HOME/script/cloud/nimbus/log.sh "4-restarts/geograph-mod-cluster" "geograph deployed"

service jboss-as-standalone restart && sh $GEOGRAPH_HOME/script/cloud/nimbus/log.sh "4-restarts/geograph-mod-cluster" "restarted torquebox"
